version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    ports: [ "5533:5432" ]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on: [ db ]
    environment:
      DATABASE_URL: postgresql+psycopg2://shop:shop@db:5432/shop
    ports: [ "8000:8000" ]

volumes:
  dbdata:
